version: "3.8"
services:
  my-alexa-skill:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
